// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails(
                          username,
                          email,
                          secret
)VALUES (
         $1, $2, $3
        )
RETURNING id, username, email, secret, is_used, created_at, expire_at
`

type CreateVerifyEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Secret   string `json:"secret"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, createVerifyEmail, arg.Username, arg.Email, arg.Secret)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Secret,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpireAt,
	)
	return i, err
}

const updateVerifyEmail = `-- name: UpdateVerifyEmail :one
UPDATE verify_emails
SET is_used = true
WHERE
    id = $1
    AND secret = $2
    AND is_used = false
    AND expire_at > now()
RETURNING id, username, email, secret, is_used, created_at, expire_at
`

type UpdateVerifyEmailParams struct {
	ID     int64  `json:"id"`
	Secret string `json:"secret"`
}

func (q *Queries) UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRow(ctx, updateVerifyEmail, arg.ID, arg.Secret)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Secret,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpireAt,
	)
	return i, err
}
